name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test1-test
      id: test1-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 30
        setup-command: pip install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1-TEST_RESULTS: "${{steps.test1-test.outputs.result}}"
      with:
        runners: test1-test
